title: Merlot
title-zh: 吟游
description: 一川烟草，满城风絮，梅子黄时雨 #>- # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://github.com/merlotliu" # the base hostname & protocol for your site, e.g. http://example.com
avatar: /assets/avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /assets/bg.jpeg

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - merlotliu-notes/

lang: en

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Merlot Liu
  url: https://github.com/merlotliu/
  email: meetlouisliu@163.com